---
- name:        Install Docker
  hosts:       docker
  become:      yes
  become_user: root
  remote_user: opc
  tasks:
  - name: Start a container
    docker_container:
      name:  oracle_xe
      image: oracleinanutshell/oracle-xe-11g
      state: started
      ports:
        - "1521:1521"
        - "8080:8080"
