---
- name:        Install Dockerised MySQL
  hosts:       docker
  become:      yes
  become_user: root
  remote_user: opc
  tasks:
  - name: Start a container
    docker_container:
      name:  mysql-server
      image: mysql/mysql-server
      state: started
      ports:
        - "3306:3306"
      env:
        MYSQL_ROOT_PASSWORD: mysql
