---
- name:        Install Docker
  hosts:       docker
  become:      yes
  become_user: root
  remote_user: opc
  tasks:
#  - name: Pull image oracle-xe-11g
#    community.docker.docker_image:
#      name:   oracleinanutshell/oracle-xe-11g
#      source: pull
#      # Select platform for pulling. If not specified, will pull whatever docker prefers.
#      #     pull:
#      #           platform: amd64
  - name: Start a container
    docker_container:
      name:  oracle_xe
      image: oracleinanutshell/oracle-xe-11g
      state: started
#      restart: yes
#      links:
#        - "myredis:aliasedredis"
#      devices:
#        - "/dev/sda:/dev/xvda:rwm"
      ports:
        - "1521:1521"
        - "8080:8080"
#        - "127.0.0.1:8081:9001/udp"
#      env:
#        SECRET_KEY: "ssssh"
#        # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
#        #         BOOLEAN_KEY: "yes"
